### ISSUE TITLE
大佬厉害啊！问个小问题

### ISSUE THREAD

**Issue by ZengHongHua** [HitenDev/JKCardLayout#1]
我下载你的项目，可以跑，但是导不了R文件.
项目可以正常运行。
可以看图，不知道是不是环境的问题，还是少传了什么文件，一定要androidx的版本才可以吗
https://res.cloudinary.com/liuyuesha/image/upload/ar_16:9,c_fill,g_auto,e_sharpen/v1550283722/r1_ptmukd.jpg
https://res.cloudinary.com/liuyuesha/image/upload/ar_16:9,c_fill,g_auto,e_sharpen/v1550283733/R2_x6brof.jpg

**Comment by HitenDev** [comment]
你用哪个版本的AS？另外可以不用androidx的版本

**Comment by ZengHongHua** [comment]
我的AS版本是3.1.3，目测应该是as版本问题。

**Comment by HitenDev** [comment]
删除项目.idea目录，然后重启AS试试；；；另外仓库更新了，欢迎更新代码跑一下效果

**Comment by HitenDev** [comment]
现在已经从androidx恢复到support了，
