### ISSUE TITLE
在卡片界面进入一个新界面，无法操作上下一个卡片。

### ISSUE THREAD

**Issue by ZengHongHua** [HitenDev/JKCardLayout#2]
可能需求有点奇怪...
在卡片界面，进入了新页面（比如详情页面），在新页面操作卡片下一个或者上一个，
mCardLayoutHelper.canNext()，mCardLayoutHelper.canBack()  这2个方法第一次会返回true,
第二次以后就返回false了, 也就导致操作不了上下卡片了。
现象就是：在新界面操作了多次下一个卡片，再回到卡片界面后，才会仅执行一次下一个卡片。
是因为界面onPause后无法执行动画的原因吗，求解答下，
怎么能做到不在卡片界面可以自由切换上下卡片呢！

**Comment by HitenDev** [comment]
我感觉应该是个bug，但我没有看明白你的问题描述，方便的话加我qq:742021130，感谢你的持续关注
