### ISSUE TITLE
如何在滑动后中获取最顶层的View

### ISSUE THREAD

**Issue by netdolphin** [HitenDev/JKCardLayout#3]
新手请教，多谢！
我在滑动卡片的时候需要获取最顶层的View，
在CardLayoutHelper.setOnCardLayoutListener中的onStateChanged方法中想获取它,试过几个方法都不行，或者得到的不准确。

**Comment by netdolphin** [comment]
发现CardLayoutHelper文件中，279行 if (mRecyclerView.getAdapter() != null) {
                        mRecyclerView.getAdapter().notifyDataSetChanged();}
 mRecyclerView.getAdapter().notifyDataSetChanged()之后，recyle的view其实是没有发现变化的。但是在adapter.OnItemClickListener中已经发现变化

**Comment by HitenDev** [comment]
解决了就好
